[theme.overrides]
idle_bg = "#111e35"
idle_fg = "#c3c6cc"
info_bg = "#c3c6cc"
info_fg = "#111e35"
good_bg = "#29A2B8"
good_fg = "#111e35"
warning_bg = "#5DA5B7"
warning_fg = "#111e35"
critical_bg = "#2898A6"
critical_fg = "#111e35"
alternating_tint_bg = "#111e35"
alternating_tint_fg = "#111e35"
